### ISSUE TITLE
Cedar-iOS target doesn't build with Xcode 5.1

### ISSUE THREAD

**Issue by sgravrockdf** [pivotal/cedar#191]
When building the Cedar-iOS target with Xcode 5.1, I get the following error:

```
[...]/cedar/Source/iPhone/CedarApplicationDelegate.m:30:78: error: cast to 'id' from smaller integer type 'int' [-Werror,-Wint-to-pointer-cast]
        [application performSelector:_terminateWithStatusSelector withObject:(id)status];
                                                                             ^
```

Casting to intptr_t before casting to id fixes it. So does declaring _terminateWithStatus: in a category with a parameter type of int and calling it directly instead of using performSelector:withObject: The latter solution is probably more correct, but it's hard to be sure without knowing what _terminateWithStatus: looks like.
